### ISSUE TITLE
Linea del tiempo sobre la web 1.0,2.0,3.0

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-7-Ariadnamonserrat10#1]
![linea del tiempo ](https://user-images.githubusercontent.com/112223282/195965882-118bad66-b262-47c6-b333-fde7ab61384a.png)
Ariadna Monserrar Lopez Aparicio 1BS

**Comment by ErikCuevas03** [comment]
20, el trabajo es visible y esta bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
